PREP_COLS = [
    "Entity Type",
    "Entity OID",
    "Entity Name",
    "Course OID",
    "Course Type",
    "Prefix",
    "Code",
    "Name",
    "Credits:",
    "When Offered:",
    "Description (Rendered no HTML)",
    "Prerequisite(s): (Rendered no HTML)",
    "Corequisite(s): (Rendered no HTML)",
    "Is Active",
    "Program Usage",
    "Program OIDs",
]

PREP_COLS_AND_TYPES = {
    "Entity Type": str,
    "Entity OID": str,
    "Entity Name": str,
    "Course OID": str,
    "Course Type": str,
    "Prefix": str,
    "Code": str,
    "Name": str,
    "Credits:": str,
    "When Offered:": str,
    "Description (Rendered no HTML)": str,
    "Prerequisite(s): (Rendered no HTML)": str,
    "Corequisite(s): (Rendered no HTML)": str,
    "Is Active": str,
    "Program Usage": str,
    "Program OIDs": str,
}
